import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const types = { '.html':'text/html; charset=utf-8', '.js':'text/javascript; charset=utf-8', '.css':'text/css; charset=utf-8', '.json':'application/json; charset=utf-8', '.svg':'image/svg+xml' };
const server = createServer(async (request, response) => {
  try {
    const requested = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    const file = path.resolve(root, `.${requested === '/' ? '/index.html' : requested}`);
    if (!file.startsWith(`${root}/`)) { response.writeHead(403); response.end(); return; }
    response.writeHead(200, {'Content-Type': types[path.extname(file)] || 'application/octet-stream'});
    response.end(await readFile(file));
  } catch { response.writeHead(404); response.end('Not found'); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const url = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? {executablePath: process.env.CHROMIUM_PATH} : {}), args: ['--no-sandbox'] });
const errors = [];
try {
  const page = await browser.newPage({ viewport: {width:1280, height:900}, deviceScaleFactor:1 });
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await page.goto(url);
  await page.waitForSelector('.js-ready');
  const visibleCount = async selector => page.locator(`${selector}:visible`).count();
  assert.equal(await visibleCount('.course-card'), 6);
  assert.match(await page.locator('#result-count').textContent(), /6 類課程 · 95 個主題/);
  await page.locator('[data-filter="national"]').click();
  assert.equal(await visibleCount('.course-card'), 5);
  assert.match(await page.locator('#result-count').textContent(), /85 個主題/);
  await page.locator('[data-filter="school"]').click();
  assert.equal(await visibleCount('.course-card'), 1);
  assert.match(await page.locator('#result-count').textContent(), /10 個主題/);
  await page.locator('[data-filter="all"]').click();
  await page.locator('#topic-search').fill('口腔');
  assert.equal(await visibleCount('.course-card'), 1);
  assert.equal(await visibleCount('.topic-list li'), 1);
  assert.match(await page.locator('#result-count').textContent(), /1 類課程 · 1 個符合主題/);
  assert.equal(await page.locator('[data-course="health-pe"] details').getAttribute('open'), '');
  await page.locator('#topic-search').fill('不存在的測試主題');
  assert.equal(await visibleCount('.course-card'), 0);
  assert.equal(await visibleCount('.empty-state'), 1);
  await page.locator('.reset-button').click();
  assert.equal(await visibleCount('.course-card'), 6);
  assert.equal(await page.locator('#topic-search').inputValue(), '');
  assert.equal(await page.locator('[data-filter="all"]').getAttribute('aria-pressed'), 'true');
  await page.locator('#topic-search').fill('閩南');
  assert.equal(await visibleCount('.course-card'), 1);
  assert.equal(await page.locator('.course-card:visible').getAttribute('data-course'), 'language-choice');
  await page.locator('.search-clear').click();
  assert.equal(await page.locator('#topic-search').inputValue(), '');
  assert.equal(await page.locator('#topic-search').evaluate(el => document.activeElement === el), true);
  await page.locator('#topic-search').fill('１０以內');
  assert.equal(await visibleCount('.course-card'), 1);
  assert.equal(await page.locator('.course-card:visible').getAttribute('data-course'), 'mathematics');
  await page.locator('#topic-search').fill('<img src=x onerror=alert(1)>');
  assert.equal(await page.locator('.empty-state img').count(), 0);
  assert.ok((await page.locator('#empty-message').textContent()).includes('<img src=x'));
  await page.locator('.reset-button').click();
  await page.locator('.expand-all').click();
  assert.equal(await page.locator('.course-details[open]').count(), 6);
  assert.equal(await visibleCount('.topic-list li'), 95);
  await page.locator('.expand-all').click();
  assert.equal(await page.locator('.course-details[open]').count(), 0);
  const summary = page.locator('.course-details summary').first();
  await summary.focus(); await page.keyboard.press('Enter');
  assert.equal(await page.locator('.course-details[open]').count(), 1);
  await page.keyboard.press('Space');
  assert.equal(await page.locator('.course-details[open]').count(), 0);
  await page.evaluate(() => window.dispatchEvent(new Event('beforeprint')));
  assert.equal(await page.locator('.course-details[open]').count(), 6);
  await page.evaluate(() => window.dispatchEvent(new Event('afterprint')));
  assert.equal(await page.locator('.course-details[open]').count(), 0);
  await page.locator('.grade-button[aria-current="true"]').click();
  assert.equal(await page.locator('#catalog-title').evaluate(el => el === document.activeElement), true);
  await mkdir(path.join(root, 'review'), {recursive: true});
  for (const width of [333, 390, 768, 1280]) {
    await page.setViewportSize({width, height:900});
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.waitForTimeout(120);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Horizontal overflow at ${width}px`);
    const cards = await page.locator('.course-card').evaluateAll(nodes => nodes.map(el => { const r=el.getBoundingClientRect(); return {left:r.left, right:r.right, width:r.width}; }));
    assert.ok(cards.every(card => card.left >= 0 && card.right <= width), `Card clipping at ${width}px`);
    if (width === 333 || width === 1280) await page.screenshot({path:path.join(root,'review',`homepage-${width}.png`),fullPage:true});
  }
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).scrollBehavior), 'auto');
  const fallback = await browser.newContext({javaScriptEnabled:false, viewport:{width:390,height:844}});
  const nojs = await fallback.newPage();
  await nojs.goto(url);
  assert.equal(await nojs.locator('.course-card').count(), 6);
  assert.equal(await nojs.locator('.topic-list li').count(), 95);
  await nojs.locator('.course-details summary').first().click();
  assert.equal(await nojs.locator('.course-details[open]').count(), 1);
  assert.equal(await nojs.locator('.search:visible').count(), 0);
  await fallback.close();
  assert.deepEqual(errors, [], 'Browser console/page errors');
  console.log('PASS: Browser rendering at 333/390/768/1280px; search, normalization, reset, filters, language choices, empty state, safe text insertion, expand/collapse, keyboard Enter/Space, print restore, current-grade focus, reduced motion, no-JS fallback; no console errors. Actual screenshots saved in review/.');
} finally { await browser.close(); server.close(); }
